### ISSUE TITLE
Expose API to resolve conflicting saves

### ISSUE THREAD

**Issue by Seldom-SE** [rustunit/bevy_ios_gamecenter#8]
See https://developer.apple.com/documentation/gamekit/saving_the_player_s_game_data_to_an_icloud_account/#4277691

Thanks!

**Comment by extrawurst** [comment]
@Seldom-SE makes sense. would you be willing to contribute it? I would give you guidance if needed

**Comment by Seldom-SE** [comment]
This is for work, and we have other priorities rn, but we plan to get to it eventually if no one else does first

**Comment by extrawurst** [comment]
@Seldom-SE would be great if you could give #9 a test. let me know if you need help to get a local setup to work that uses a non-released version of this

**Comment by Seldom-SE** [comment]
> let me know if you need help to get a local setup to work that uses a non-released version of this

@extrawurst Yes, please. I replaced the remote package dependency with a clone of your branch, and I'm getting linker errors.

<img width="404" alt="Screenshot 2024-11-20 at 2 51 04 PM" src="https://github.com/user-attachments/assets/361d15a0-a471-4405-8ff3-c90a20510bf0">

**Comment by extrawurst** [comment]
So you checkout `bevy_ios_gamecenter` locally. its important to build the binary framework in it: `just build` and switch the dependency in xcode to a local one pointing to the local checkout. of course you also need to point your bevy projects dependency to the local crate. After that build&run in xcode should work.

* checkout `bevy_ios_gamecenter` locally
* `just build` in root of it
* change xcode package dependency to local package
* Change the framework binary used in the swift `package.swift` (the needed config is in there but [commented](https://github.com/rustunit/bevy_ios_gamecenter/blob/4c117ca2d72ac321b5ae6a4114aeaa6a3b75a8cf/Package.swift#L20) out)
* change bevy project `cargo.toml` dependency also to the local checkout (the subfolder that is)

edit: I forgot step 4 please note that one

**Comment by extrawurst** [comment]
Btw. I found a nice way to make the API more like `bevy_mod_reqwest` observer based in `bevy_ios_iap`: https://github.com/rustunit/bevy_ios_iap/tree/support-subscriptions i am planning to add the same here

**Comment by Seldom-SE** [comment]
Oooh, that could help clean things up a lot. I could just move some context into an observer's closure
